# Generated by Django 3.2.6 on 2021-08-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='别名')),
                ('username', models.CharField(max_length=128, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='用户密码')),
                ('protocol_type', models.CharField(choices=[('SSH2', 'Ssh2'), ('RDP', 'RDP'), ('VNC', 'RNV')], max_length=6, verbose_name='协议类型')),
                ('server', models.CharField(max_length=16, verbose_name='ipv4')),
                ('port', models.CharField(max_length=5, verbose_name='端口')),
            ],
        ),
    ]
