# Generated by Django 3.2.6 on 2021-11-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('content', models.TextField(verbose_name='命令内容')),
            ],
            options={
                'verbose_name': 'command_log',
                'verbose_name_plural': 'command_log',
                'db_table': 'command_log',
            },
        ),
    ]
