# Generated by Django 3.2.6 on 2021-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0002_commandlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('path', models.FilePathField(match='/media/', verbose_name='屏幕记录')),
            ],
            options={
                'verbose_name': 'screen_record',
                'verbose_name_plural': 'screen_record',
                'db_table': 'screen_record',
            },
        ),
    ]
