# Generated by Django 3.2.6 on 2021-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_alter_screenrecord_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenrecord',
            name='protocol',
            field=models.CharField(blank=True, choices=[('ssh2', 'ssh2'), ('rdp', 'rdp'), ('telnet', 'telnet'), ('ssh', 'ssh')], default='ssh2', max_length=10, null=True, verbose_name='协议类别'),
        ),
    ]
