# Generated by Django 3.2.6 on 2021-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_auto_20211110_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
